name: CI-Primary
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  prod_deploy:
    runs-on: [ self-hosted, prod ]
    if: endswith(github.ref, 'main')
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - name: Install
        run: |
          python3 -m venv env
          pip install --upgrade pip
          source env/bin/activate
          pip3 install -r requirements.txt
      - name: Run
        run: |
          pip3 install -U -r requirements.txt
          python3 main.py
